### ISSUE TITLE
Need to opt-out of Browzine services

### ISSUE THREAD

**Issue by Steve-A-Orr** [thirdiron/browzine-discovery-service-adapters#32]
As shared recently with Third Iron staff (Tian, Jordan, and John) in a technical support email chain for the Primo adapter, some libraries may desire to avoid displaying either the Article or Journal web links, as well as possibly cancel the use of the Browzine Cover Images.

Controlling the use of each service (two Web links and Cover Image) can be accomplished with the _non-mandatory_ introduction of only one variable (to the existing two variables) in the Primo **custom.js** file. 

I'll provide a pull request with the required adapter code changes. After loading the library:

- the proposed "primoUseCoverImageBrowZineService" variable needs to be set to **false** to avoid using cover images.
- either of the existing variables need to be set to an empty string ("") to stop showing web links for that type.

**Comment by johnseguin** [comment]
Hi Steve, 

I'm closing this issue since in more recent versions we did add a similar functionality.  You can see where these flags are at (and we kept your idea going with other new features, always allowing them to be turned "off").  We recently added an option to turn on unpaywall data as well within the integration which you may bae interested in as well!

Thanks,
John

**Comment by Steve-A-Orr** [comment]
I will certainly look at your improvements. Thank you for telling me.
